version: 0.2

phases:
  pre_build:
    commands:
      - echo GODOT_VERSION=$GODOT_VERSION
      - echo GODOT_IMAGE_NAME=$GODOT_IMAGE_NAME
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $GODOT_IMAGE_NAME:$GODOT_VERSION .
      - docker tag $GODOT_IMAGE_NAME:$GODOT_VERSION public.ecr.aws/f7u9w0t1/$GODOT_IMAGE_NAME:$GODOT_VERSION      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/f7u9w0t1/$GODOT_IMAGE_NAME:$GODOT_VERSION